### ISSUE TITLE
Wrong USB charging status detection

### ISSUE THREAD

**Issue by WanderMax** [joel16/VITAident#5]
I run my PSV1000 in henkaku 8 with USB charging on in setting.
But in the VITAident, I find that the USB charging status is shown as disabled.
I switch the USB charging off then on, the status detection is still wrong.
Could you please check that whether it is one bug?
Thanks.

**Comment by joel16** [comment]
Hello WanderMax, 
Thanks for reporting the issue. Does this issue occur if it's connected to the AC adapter or PC?

By, "I switch the USB charging off then on" are you referring to "USB power suppy" in system settings?
And does it show the charging animation when you are connected?

Anyways from what I know, it should display as USB charging enabled if your usb is connected to an AC adapter. However, if it is connected to the PC, it won't display as "enabled" because there simply isn't enough amps to charge the VITA. Believe it or not, but I don't think USB charging works on the VITA. I heard the only way to charge the VITA with a PC is if you power off the vita (not stand-by) and then connect it to the PC.

**Comment by WanderMax** [comment]
@joel16 Yes, when connected to PC, it shows disable. 
I will check whether it shows correct status when  connected to the AC adapter.

Now I know that the status of USB charging (enable/disable) is the current charging status, not the ON/OFF in PSV setting page.
I suggest that you can modify the strings, or it may cause misunderstanding.
Thanks.

**Comment by joel16** [comment]
Alright this commit should fix the issue https://github.com/joel16/VITAident/commit/dd2ddaab4be0efd0f6099a8a1e19d5d6a2f6c953.

I have tested it and can confirm that it now properly detects whether USB power supply is enabled/disabled.
